# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- none
variables:
  majorVersion: 2
  minorVersion: $[counter(variables['majorVersion'], 0)]
  patchVersion: $[counter(format('{0}.{1}', variables['majorVersion'], variables['minorVersion']), 0)]
  versionNumber: '$(majorVersion).$(minorVersion).$(patchVersion)'


pool: ubuntupool

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '10.19.0'
    checkLatest: true

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './'
    verbose: true

- task: Bash@3
  displayName: 'Update Version'
  inputs:
      targetType: 'inline'
      script: |
          echo "Current Version: $(versionNumber)"
          npm --no-git-tag-version version $(versionNumber) --allow-same-version

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    StoreAsTar: true
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: './'
    verbose: true
    publishRegistry: 'useFeed'
    publishFeed: '9d4a9b0f-64ae-4c9d-b784-5cc5500f5db0'
